services:
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: . # Current directory
        target: /backend # The container's work_dir which is /backend
      - type: volume
        source: database # Name of a volume that gets created at line 14/15
        target: /db.sqlite3

volumes:
  database: