services:
  django:
    build: .
    ports:
      - "8000:8000"
    volumes: #bind mount that takes the current local directory (Which is Tindeggle on local machine) and binds it to:
      - .:/backend # The container's work_dir which is /backend