# Generated by Django 4.1.7 on 2023-03-21 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, help_text='Tell Everyone About Yourself.', max_length=500)),
                ('ppic1', models.ImageField(upload_to='')),
                ('ppic2', models.ImageField(blank=True, upload_to='')),
                ('ppic3', models.ImageField(blank=True, upload_to='')),
                ('ppic4', models.ImageField(blank=True, upload_to='')),
                ('ppic5', models.ImageField(blank=True, upload_to='')),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(blank=True, choices=[('Anime', 'Anime'), ('K-Pop', 'K-Pop'), ('K-Shows', 'K-Shows'), ('Webtoon', 'Webtoon'), ('American Shows', 'American Shows'), ('Movies', 'Movies'), ('Food', 'Food'), ('Yoga', 'Yoga'), ('Working Out', 'Working Out'), ('Fighting', 'Fighting'), ('Cars', 'Cars'), ('Business', 'Business'), ('Stocks', 'Stocks'), ('School', 'School'), ('Relationship', 'Relationship'), ('Deep Talks', 'Deep Talks'), ('Controversial Subjects', 'Controversial Subjects'), ('Video Games', 'Video Games'), ('Sports', 'Sports')], max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.profile')),
            ],
        ),
    ]
