# Generated by Django 4.1.7 on 2023-03-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0002_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ppic6',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
