# Generated by Django 4.1.7 on 2023-03-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_profile_ppic6'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interests',
            new_name='Interest',
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(help_text="   Type exactly like: 'YYYY-MM-DD'"),
        ),
    ]
