# Generated by Django 4.1.7 on 2023-03-22 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_rename_interests_interest_alter_profile_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('room_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.chatroom')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=300)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('chatRoom', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='match.chatroom')),
                ('profile', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='match.profile')),
            ],
        ),
    ]
