# Generated by Django 4.1.7 on 2023-03-23 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0005_chatroom_profile_age_participant_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileOther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileOther', to='match.profile')),
                ('profileUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileUser', to='match.profile')),
            ],
        ),
    ]
