# Generated by Django 4.1.7 on 2023-03-23 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0006_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(blank=True, choices=[('like', 'like'), ('not like', 'note like')], max_length=30)),
                ('profileOther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileOther', to='match.profile')),
                ('profileUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileUser', to='match.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
