# Generated by Django 4.1.5 on 2023-03-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0007_relationship_delete_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='relationship',
            field=models.CharField(blank=True, choices=[('like', 'like'), ('not like', 'not like'), ('unseen', 'unseen')], default='unseen', max_length=30),
        ),
    ]
