# Generated by Django 4.1.7 on 2023-03-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0008_alter_relationship_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='relationship',
            field=models.CharField(blank=True, choices=[('like', 'like'), ('not like', 'not like')], max_length=30),
        ),
    ]
