# Generated by Django 4.1.7 on 2023-03-30 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0009_alter_relationship_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='match.profile'),
        ),
    ]
