# Generated by Django 4.1.7 on 2023-03-30 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0010_alter_interest_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='interest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='match.profile'),
        ),
    ]
