# Generated by Django 4.1.7 on 2023-04-06 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0021_alter_message_chatroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='groupChatRoom',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='match.groupchatroom'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='chatRoom',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='match.chatroom'),
        ),
    ]
